### ISSUE TITLE
A bunch of warnings

### ISSUE THREAD

**Issue by inoyakaigor** [rickbrenn/refit#2]
Just installed and run `refit w` and got these:

```
Warning: LoaderBoundary: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.
    at LoaderBoundary (webpack://refit/./src/ui/LoaderBoundary.js?:12:3)
    at WizardCommand (webpack://refit/./src/commands/Wizard/index.js?:42:3)
    at ErrorProvider (webpack://refit/./src/ui/ErrorBoundary/ErrorProvider.js?:13:3)
    at ErrorBoundary (webpack://refit/./src/ui/ErrorBoundary/ErrorBoundary.js?:27:5)
    at App (file:///C:/Users/InoY/AppData/Roaming/npm/node_modules/refit/node_modules/ink/build/components/App.js:19:9)
Warning: Loader: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.
    at Loader (webpack://refit/./src/ui/Loader.js?:12:3)
    at LoaderBoundary (webpack://refit/./src/ui/LoaderBoundary.js?:12:3)
    at WizardCommand (webpack://refit/./src/commands/Wizard/index.js?:42:3)
    at ErrorProvider (webpack://refit/./src/ui/ErrorBoundary/ErrorProvider.js?:13:3)
    at ErrorBoundary (webpack://refit/./src/ui/ErrorBoundary/ErrorBoundary.js?:27:5)
    at App (file:///C:/Users/InoY/AppData/Roaming/npm/node_modules/refit/node_modules/ink/build/components/App.js:19:9)
Warning: Wizard: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.
    at Wizard (webpack://refit/./src/ui/Wizard.js?:13:3)
    at ink-box
    at file:///C:/Users/InoY/AppData/Roaming/npm/node_modules/refit/node_modules/ink/build/components/Box.js:5:27
    at UpToDateBoundary (webpack://refit/./src/ui/UpToDateBoundary.js?:12:3)
    at LoaderBoundary (webpack://refit/./src/ui/LoaderBoundary.js?:12:3)
    at WizardCommand (webpack://refit/./src/commands/Wizard/index.js?:42:3)
    at ErrorProvider (webpack://refit/./src/ui/ErrorBoundary/ErrorProvider.js?:13:3)
    at ErrorBoundary (webpack://refit/./src/ui/ErrorBoundary/ErrorBoundary.js?:27:5)
    at App (file:///C:/Users/InoY/AppData/Roaming/npm/node_modules/refit/node_modules/ink/build/components/App.js:19:9)
Warning: FocusTarget: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.
    at FocusTarget (webpack://refit/./src/ui/FocusTarget.js?:12:3)
    at DependencyStep (webpack://refit/./src/commands/Wizard/DependencyStep.js?:26:3)
    at Wizard (webpack://refit/./src/ui/Wizard.js?:13:3)
    at ink-box
    at file:///C:/Users/InoY/AppData/Roaming/npm/node_modules/refit/node_modules/ink/build/components/Box.js:5:27
    at UpToDateBoundary (webpack://refit/./src/ui/UpToDateBoundary.js?:12:3)
    at LoaderBoundary (webpack://refit/./src/ui/LoaderBoundary.js?:12:3)
    at WizardCommand (webpack://refit/./src/commands/Wizard/index.js?:42:3)
    at ErrorProvider (webpack://refit/./src/ui/ErrorBoundary/ErrorProvider.js?:13:3)
    at ErrorBoundary (webpack://refit/./src/ui/ErrorBoundary/ErrorBoundary.js?:27:5)
    at App (file:///C:/Users/InoY/AppData/Roaming/npm/node_modules/refit/node_modules/ink/build/components/App.js:19:9)
Warning: Selector: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.
    at Selector (webpack://refit/./src/ui/Selector/Selector.js?:18:3)
    at ink-box
    at file:///C:/Users/InoY/AppData/Roaming/npm/node_modules/refit/node_modules/ink/build/components/Box.js:5:27
    at FocusTarget (webpack://refit/./src/ui/FocusTarget.js?:12:3)
    at DependencyStep (webpack://refit/./src/commands/Wizard/DependencyStep.js?:26:3)
    at Wizard (webpack://refit/./src/ui/Wizard.js?:13:3)
    at ink-box
    at file:///C:/Users/InoY/AppData/Roaming/npm/node_modules/refit/node_modules/ink/build/components/Box.js:5:27
    at UpToDateBoundary (webpack://refit/./src/ui/UpToDateBoundary.js?:12:3)
    at LoaderBoundary (webpack://refit/./src/ui/LoaderBoundary.js?:12:3)
    at WizardCommand (webpack://refit/./src/commands/Wizard/index.js?:42:3)
    at ErrorProvider (webpack://refit/./src/ui/ErrorBoundary/ErrorProvider.js?:13:3)
    at ErrorBoundary (webpack://refit/./src/ui/ErrorBoundary/ErrorBoundary.js?:27:5)
    at App (file:///C:/Users/InoY/AppData/Roaming/npm/node_modules/refit/node_modules/ink/build/components/App.js:19:9)
Warning: List: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.
    at List (webpack://refit/./src/ui/Selector/common/List.js?:14:3)
    at Selector (webpack://refit/./src/ui/Selector/Selector.js?:18:3)
    at ink-box
    at file:///C:/Users/InoY/AppData/Roaming/npm/node_modules/refit/node_modules/ink/build/components/Box.js:5:27
    at FocusTarget (webpack://refit/./src/ui/FocusTarget.js?:12:3)
    at DependencyStep (webpack://refit/./src/commands/Wizard/DependencyStep.js?:26:3)
    at Wizard (webpack://refit/./src/ui/Wizard.js?:13:3)
    at ink-box
    at file:///C:/Users/InoY/AppData/Roaming/npm/node_modules/refit/node_modules/ink/build/components/Box.js:5:27
    at UpToDateBoundary (webpack://refit/./src/ui/UpToDateBoundary.js?:12:3)
    at LoaderBoundary (webpack://refit/./src/ui/LoaderBoundary.js?:12:3)
    at WizardCommand (webpack://refit/./src/commands/Wizard/index.js?:42:3)
    at ErrorProvider (webpack://refit/./src/ui/ErrorBoundary/ErrorProvider.js?:13:3)
    at ErrorBoundary (webpack://refit/./src/ui/ErrorBoundary/ErrorBoundary.js?:27:5)
    at App (file:///C:/Users/InoY/AppData/Roaming/npm/node_modules/refit/node_modules/ink/build/components/App.js:19:9)
```
![image](https://github.com/rickbrenn/refit/assets/1235286/3f5d6a46-0d66-4705-885d-330127df2a75)

**Comment by rickbrenn** [comment]
The latest version of React warns about the deprecation of `defaultProps`. I'll replace those and push up a fix, Thanks!

**Comment by rickbrenn** [comment]
This is resolved in the latest release https://github.com/rickbrenn/refit/releases/tag/v1.0.1
